$('.owl-carousel').owlCarousel({
    loop:true,
    margin:6,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        500:{
            items:4
        },
        1100:{
            items:6
        }
    }
})